cask_args appdir: '/Applications', require_sha: true

tap 'hashicorp/tap', trusted: true

# ----------------------------------------------------------------------------------------------------------
brew 'bash'
brew 'bat'
brew 'btop'
brew 'colima'
brew 'curl'
brew 'direnv'
brew 'docker'
brew 'docker-buildx'
brew 'docker-compose'
brew 'docker-credential-helper'
brew 'eza'
brew 'fd'
brew 'fzf'
brew 'git'
brew 'git-delta'
brew 'git-extras'
brew 'git-interactive-rebase-tool'
brew 'go'
brew 'hashicorp/tap/terraform'
brew 'helm'
brew 'jq'
brew 'k3d'
brew 'k9s'
brew 'kubernetes-cli'
brew 'lima-additional-guestagents'
brew 'luarocks'
brew 'mas'
brew 'mise'
brew 'neovim'
brew 'ripgrep'
brew 'stow'
brew 'tig'
brew 'tlrc'
brew 'tmux'
brew 'tree-sitter-cli'
brew 'vim'
brew 'vivid'
brew 'watch'
brew 'wget'
brew 'zoxide'
brew 'zsh'

# ----------------------------------------------------------------------------------------------------------
cask '1password'
cask 'alfred'
cask 'appcleaner'
cask 'brave-browser'
cask 'claude-code'
cask 'discord'
cask 'firefox'
cask 'flycut'
cask 'font-jetbrains-mono-nerd-font'
cask 'hashicorp/tap/hashicorp-vagrant'
cask 'intellij-idea'
cask 'jordanbaird-ice'
cask 'keybase'
cask 'kitty'
cask 'rectangle'
cask 'slack'
cask 'spotify'
cask 'tailscale-app'
cask 'virtualbox'
cask 'visual-studio-code'
cask 'whatsapp'
cask 'zoom'

# ----------------------------------------------------------------------------------------------------------
mas 'Bitwarden', id: 1352778147
mas 'Velja', id: 1607635845
mas 'Yubico Authenticator', id: 1497506650

# ----------------------------------------------------------------------------------------------------------
vscode 'catppuccin.catppuccin-vsc'
vscode 'catppuccin.catppuccin-vsc-icons'
vscode 'esbenp.prettier-vscode'
# vscode 'github.copilot-chat'
vscode 'golang.go'
vscode 'hashicorp.terraform'
vscode 'ibm.output-colorizer'
vscode 'ms-azuretools.vscode-containers'
vscode 'ms-kubernetes-tools.vscode-kubernetes-tools'
vscode 'ms-vscode-remote.remote-containers'
vscode 'ms-vscode-remote.remote-ssh'
vscode 'redhat.vscode-yaml'
vscode 'rooveterinaryinc.roo-cline'
vscode 'vscode-icons-team.vscode-icons'

# https://community.cloudflare.com/t/warp-and-warp-routing-me-through-europe-instead-of-india/533920
# Not using as it is drastically reducing internet speed and increasing ping
# Picking up server in frankfut instead of a server in India.
# Will reuse once the issue is resolved.
# cask 'cloudflare-warp'
