#!/usr/bin/env zsh

symlink() {
	printf 'SYMLINK %55s -> %s\n' "${1/#$HOME/~}" "${2/#$HOME/~}"
	ln -nsf "$@"
}

copy() {
	printf 'COPY %58s -> %s\n' "${1/#$HOME/~}" "${2/#$HOME/~}"
	cp -r "$@"
}

FILES="${DOTFILES_DIR}/files"

for entry in "$FILES"/* "$FILES"/.[!.]*
do
  basename_entry=$(basename "$entry")
  [[ -d ${HOME}/$basename_entry && ! -L ${HOME}/$basename_entry ]] && rm -r "${HOME:?}/$basename_entry"

  if [[ $basename_entry == git* ]]; then
    copy "$FILES/$basename_entry" "${HOME}/.$basename_entry"
  else
    symlink "$FILES/$basename_entry" "${HOME}/$basename_entry"
  fi
done
