cask_args appdir: '/Applications', no_quarantine: true

# ----------------------------------------------------------------------------------------------------------
brew 'bash'
brew 'bat'
brew 'btop'
brew 'colima'
brew 'coreutils'
brew 'curl'
brew 'docker'
brew 'docker-buildx'
brew 'docker-compose'
brew 'docker-credential-helper'
brew 'fd'
brew 'fzf'
brew 'git'
brew 'git-delta'
brew 'git-extras'
brew 'git-interactive-rebase-tool'
brew 'gnu-sed'
brew 'go'
brew 'jq'
brew 'kubernetes-cli'
brew 'k9s'
brew 'lima-additional-guestagents'
# brew 'luarocks' # will enable after sometime
brew 'mas'
brew 'mise'
# brew 'neovim'  # will enable after sometime
brew 'powerlevel10k'
brew 'ripgrep'
brew 'tig'
brew 'tlrc'
brew 'tmux'
brew 'vim'
brew 'watch'
brew 'wget'
brew 'zoxide'
brew 'zsh'

# ----------------------------------------------------------------------------------------------------------
cask '1password'
cask 'appcleaner'
cask 'brave-browser'
cask 'cursor'
cask 'dbeaver-community'
cask 'discord'
cask 'flycut'
cask 'font-jetbrains-mono-nerd-font'
cask 'gcloud-cli'
cask 'intellij-idea'
cask 'iterm2'
cask 'keybase'
cask 'kitty'
cask 'raycast'
cask 'rectangle'
cask 'slack'
cask 'tailscale-app'
cask 'visual-studio-code'
cask 'whatsapp'
cask 'zoom'

# ----------------------------------------------------------------------------------------------------------
mas 'Bitwarden', id: 1352778147
mas 'Velja', id: 1607635845
mas 'Yubico Authenticator', id: 1497506650

# ----------------------------------------------------------------------------------------------------------
vscode 'catppuccin.catppuccin-vsc'
vscode 'catppuccin.catppuccin-vsc-icons'
vscode 'eamodio.gitlens'
vscode 'esbenp.prettier-vscode'
vscode 'github.copilot'
vscode 'github.copilot-chat'
vscode 'golang.go'
# vscode 'hashicorp.terraform'
vscode 'ibm.output-colorizer'
vscode 'ms-azuretools.vscode-containers'
vscode 'ms-vscode-remote.remote-containers'
vscode 'ms-vscode-remote.remote-ssh'
vscode 'redhat.vscode-yaml'
vscode 'rooveterinaryinc.roo-cline'
vscode 'vscode-icons-team.vscode-icons'

# https://community.cloudflare.com/t/warp-and-warp-routing-me-through-europe-instead-of-india/533920
# Not using as it is drastically reducing internet speed and increasing ping
# Picking up server in frankfut instead of a server in India.
# Will reuse once the issue is resolved.
# cask 'cloudflare-warp'
